In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("./heart_attack_risk_dataset.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      50000 non-null  int64
 1   Gender                   50000 non-null  object
 2   Smoking                  50000 non-null  int64
 3   Alcohol_Consumption      50000 non-null  int64
 4   Physical_Activity_Level  50000 non-null  object
 5   BMI                      50000 non-null  float64
 6   Diabetes                 50000 non-null  int64
 7   Hypertension             50000 non-null  int64
 8   Cholesterol_Level        50000 non-null  float64
 9   Resting_BP               50000 non-null  int64
 10  Heart_Rate               50000 non-null  int64
 11  Family_History           50000 non-null  int64
 12  Stress_Level             50000 non-null  object
 13  Chest_Pain_Type          50000 non-null  object
 14  Thalassemia              50000 non-null  object
 15  Fasting_Blood_Sugar      50000 non-null  int64
 16  ECG_Results              50000 non-null  object
 17  Exercise_Induced_Angina  50000 non-null  int64
 18  Max_Heart_Rate_Achieved  50000 non-null  int64
 19  Heart_Attack_Risk        50000 non-null  object
dtypes: float64(2), int64(11), object(7)
memory usage: 7.6+ MB

In [12]:
y = data['Heart_Attack_Risk']
df_y = pd.DataFrame(y)
data = data.drop('Heart_Attack_Risk', axis=1)
df_y['Heart_Attack_Risk'] = df_y.Heart_Attack_Risk.map({'Low':0,'Moderate':1,'High':2})
df_y.head(10)

   Heart_Attack_Risk
0                  0
1                  1
2                  0
3                  0
4                  1
5                  2
6                  0
7                  1
8                  1
9                  1

In [13]:
standard = ['Age','BMI','Cholesterol_Level','Resting_BP','Heart_Rate','Max_Heart_Rate_Achieved']
data_n = data[standard]
data_D = (data_n-data_n.mean())/data_n.std()
data = data.drop(standard, axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   50000 non-null  object
 1   Smoking                  50000 non-null  int64
 2   Alcohol_Consumption      50000 non-null  int64
 3   Physical_Activity_Level  50000 non-null  object
 4   Diabetes                 50000 non-null  int64
 5   Hypertension             50000 non-null  int64
 6   Family_History           50000 non-null  int64
 7   Stress_Level             50000 non-null  object
 8   Chest_Pain_Type          50000 non-null  object
 9   Thalassemia              50000 non-null  object
 10  Fasting_Blood_Sugar      50000 non-null  int64
 11  ECG_Results              50000 non-null  object
 12  Exercise_Induced_Angina  50000 non-null  int64
dtypes: int64(7), object(6)
memory usage: 5.0+ MB

In [14]:
# Convert the data into a pandas DataFrame
df = pd.DataFrame(data)
col = ['Gender','Smoking', 'Alcohol_Consumption','Physical_Activity_Level','Diabetes','Hypertension','Family_History','Stress_Level','Chest_Pain_Type','Thalassemia','Fasting_Blood_Sugar','ECG_Results','Exercise_Induced_Angina']
dummies = pd.get_dummies(df,columns=col)
df_onehot = pd.concat([df, dummies], axis = 1)
df_onehot = df_onehot.drop(columns=col)
df_onehot[standard] = data_D
df_onehot['Heart_Attack_Risk'] = df_y
nan_count = df_onehot.isnull().sum().sum()
print('Number of NaN values:', nan_count)
df_onehot.to_csv('cleandata_one_hot_only.csv') 
df_onehot.info()

Number of NaN values: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Gender_Female                             50000 non-null  bool
 1   Gender_Male                               50000 non-null  bool
 2   Smoking_0                                 50000 non-null  bool
 3   Smoking_1                                 50000 non-null  bool
 4   Alcohol_Consumption_0                     50000 non-null  bool
 5   Alcohol_Consumption_1                     50000 non-null  bool
 6   Physical_Activity_Level_High              50000 non-null  bool
 7   Physical_Activity_Level_Low               50000 non-null  bool
 8   Physical_Activity_Level_Moderate          50000 non-null  bool
 9   Diabetes_0                                50000 non-null  bool
 10  Diabetes_1                                50000 non-null  bool
 11  Hypertension_0                            50000 non-null  bool
 12  Hypertension_1                            50000 non-null  bool
 13  Family_History_0                          50000 non-null  bool
 14  Family_History_1                          50000 non-null  bool
 15  Stress_Level_High                         50000 non-null  bool
 16  Stress_Level_Low                          50000 non-null  bool
 17  Stress_Level_Moderate                     50000 non-null  bool
 18  Chest_Pain_Type_Asymptomatic              50000 non-null  bool
 19  Chest_Pain_Type_Atypical                  50000 non-null  bool
 20  Chest_Pain_Type_Non-anginal               50000 non-null  bool
 21  Chest_Pain_Type_Typical                   50000 non-null  bool
 22  Thalassemia_Fixed defect                  50000 non-null  bool
 23  Thalassemia_Normal                        50000 non-null  bool
 24  Thalassemia_Reversible defect             50000 non-null  bool
 25  Fasting_Blood_Sugar_0                     50000 non-null  bool
 26  Fasting_Blood_Sugar_1                     50000 non-null  bool
 27  ECG_Results_Left Ventricular Hypertrophy  50000 non-null  bool
 28  ECG_Results_Normal                        50000 non-null  bool
 29  ECG_Results_ST-T abnormality              50000 non-null  bool
 30  Exercise_Induced_Angina_0                 50000 non-null  bool
 31  Exercise_Induced_Angina_1                 50000 non-null  bool
 32  Age                                       50000 non-null  float64
 33  BMI                                       50000 non-null  float64
 34  Cholesterol_Level                         50000 non-null  float64
 35  Resting_BP                                50000 non-null  float64
 36  Heart_Rate                                50000 non-null  float64
 37  Max_Heart_Rate_Achieved                   50000 non-null  float64
 38  Heart_Attack_Risk                         50000 non-null  int64
dtypes: bool(32), float64(6), int64(1)
memory usage: 4.2 MB

In [15]:
# # Convert the data into a pandas DataFrame
# df = pd.DataFrame(data)
# # Use pd.get_dummies() to one-hot encode the categorical columns
# df_pandas_encoded = pd.get_dummies(df, columns=['Gender','Smoking', 'Alcohol_Consumption','Diabetes','Hypertension','Family_History','Fasting_Blood_Sugar','Exercise_Induced_Angina'], drop_first=True)
# # print(f"One-Hot Encoded Data using Pandas:\n{df_pandas_encoded}\n")
# categorical_columns_onehot =['Gender','Smoking', 'Alcohol_Consumption','Diabetes','Hypertension','Family_History','Fasting_Blood_Sugar','Exercise_Induced_Angina']
# # Initialize OneHotEncoder
# encoder = OneHotEncoder(sparse_output=False)

# # Fit and transform the categorical columns
# one_hot_encoded = encoder.fit_transform(df[categorical_columns_onehot])

# # Create a DataFrame with the encoded columns
# one_hot_df = pd.DataFrame(one_hot_encoded, 
#                           columns=encoder.get_feature_names_out(categorical_columns_onehot))

# # Concatenate the one-hot encoded columns with the original DataFrame
# learn_encoded = pd.concat([df.drop(categorical_columns_onehot, axis=1), one_hot_df], axis=1)
# learn_encoded.to_csv('cleandata_onehot_and_label_encoding.csv') 
# learn_encoded.head()